BASE_PATH = "data/data/nums"


BATCH_SIZE = 64
PADDING_TOKEN = 99
IMAGE_WIDTH = 128
IMAGE_HEIGHT = 32

MODEL_DIR = "models/nummodel/"
MODEL_NAME = "WORDOCR"

LOG_DIR = "logs/nummodel"

MAX_CKPT_TO = 5
EPOCHS = 50